### ISSUE TITLE
ERC721のガス代について

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#1]
・複数枚ミントする設計でERC721だとユーザーとコンストラクタでのガス代も結構かかると思いますが、
ERC721AかERC721PsiかERC721AntiScamにERC721P2Pの実装を移植するのはどうでしょうか？
大きめの変更も必要だと思うので、ここは他エンジニアの意見も聞きたいです。

**Comment by hajime001** [comment]
それかERC721P2Pにプルリク。

**Comment by masataka-eth** [comment]
僕もERC721AP2P（継承元がERC721Aver）を用意するのが良いのではと思います。
ERC721WithOperatorFilterがoverrideしている関数群は共通なので用意することは可能と思います。

ただしNFT側（pNounsToken）で以下に注意する必要があります
・tokenIDを１始まりにしたいなら_startTokenIdの設定をする
・_safeMintの第２引数の扱いが変わるので変更する

※可能ならmintCountマッピングをERC721Aのauxでやれるとガス代が安くなるので是非

**Comment by Lavulite** [comment]
複数ミント前提に見えるので私もERC721AやPsiが良いと思います。

**Comment by EibaKatsu** [comment]
ERC721A採用が決定したのでクローズさせていただきます。
masatakaさん、ありがとうございます！
