### ISSUE TITLE
mintPNouns：mintAmount確認

### ISSUE THREAD

**Issue by masataka-eth** [EibaKatsu/pNounsGenerative#10]
_mintAmount > 0 のrequireを入れたほうが安全です

**Comment by EibaKatsu** [comment]
追加しました！

            // ミント数が購入単位と一致していること,ミント数が設定されていること
            require(_mintAmount % purchaseUnit == 0 && _mintAmount > 0, "Invalid purchaseUnit");

**Comment by masataka-eth** [comment]
確認できました。
