### ISSUE TITLE
totalSupply()は正常に機能する？？

### ISSUE THREAD

**Issue by masataka-eth** [EibaKatsu/pNounsGenerative#12]
totalSupply()ってProviderToken2のものがコールされるのでは？
そうだとすると成立しないのでかなりマズイです。

**Comment by EibaKatsu** [comment]
テストコードでは問題なく動作しているように見えています。
本来やるべき実装があれば教えてください！

![image](https://user-images.githubusercontent.com/98363905/204931443-97817dfc-3038-4f38-a894-43718380ae83.png)

**Comment by Lavulite** [comment]
ProviderToken2のものが利用されているように思いますが、burnがないので特に問題ないのではないでしょうか？
nextTokenIdを参照しており、nextTokenIdは0スタートなのでburnがない限りは総供給量と一致すると思います。

**Comment by EibaKatsu** [comment]
テストコード追加しました。

```
      const [count] = await token.functions.totalSupply();
      await token.setMintLimit(count.toNumber()+1);
      const [mintLimit] = await token.functions.mintLimit();

      // 1つ目はエラーにならない
      token.functions.mintPNouns( 1, proof, { value: 0 });
      // 2つ目はエラーになる
      await expect(token.functions.mintPNouns( 1, proof, { value: 0 }))
      .to.be.revertedWith("Sold out");
```

**Comment by masataka-eth** [comment]
テストコード確認しました。
ProviderToken3.sol→totalSupplyもコメントアウトしても意図通りの動作をしているので、安心と思います。

クローズします。
