### ISSUE TITLE
withdrawを入れることを推奨

### ISSUE THREAD

**Issue by masataka-eth** [EibaKatsu/pNounsGenerative#13]
mintする度にトレジャリーに送金される仕様だが、念のため念のためwithdrawは入れておいた方が安全です
（不具合でコントラクトに溜まってしまったらwithdrawでトレジャリーに送金する）

**Comment by EibaKatsu** [comment]
mintする度にトレジャリーに送金される仕様でしたが、潜在的なリスクを抱えることになるので宜しくないという情報があったので、廃止して withdrawで引き出すことにしました。

https://solidity-jp.readthedocs.io/ja/latest/common-patterns.html

**Comment by masataka-eth** [comment]
確認できました。
※意図通りに引き出しできることを必ずテストを入れて下さい

**Comment by EibaKatsu** [comment]
テストコード追加しました
[https://github.com/EibaKatsu/pNounsGenerative/commit/af4a36d68687a2eeefb2f9016e8223b1e0afe204](url)
