### ISSUE TITLE
PublicSaleは利用されていないので不要ではないでしょうか

### ISSUE THREAD

**Issue by Lavulite** [EibaKatsu/pNounsGenerative#15]
SalePhaseのPublicSaleは利用していないのでミスリードを避けるために消した方が良いように思います。

**Comment by EibaKatsu** [comment]
PublicSaleはチェックすることがなかったので省略していました。
わかりやすくするために以下追加しました。

![image](https://user-images.githubusercontent.com/98363905/205175422-f84501bc-e39f-4806-8b0b-1e858e0eb431.png)

**Comment by EibaKatsu** [comment]
テストがなかったのでテストも追加しました

**Comment by Lavulite** [comment]
なるほど。ご説明ありがとうございます。クローズしますね。
