### ISSUE TITLE
Callevel 0でマケプレ全拒否でokか

### ISSUE THREAD

**Issue by cryptedy** [EibaKatsu/pNounsGenerative#18]
CALのチャンネルで将来的に独自マケプレの話がありましたが、現状は0にした段階でCALによらず全拒否の実装です。approve関連を使わないP2Pを指しているなら問題はないと思いますが、そうでないならCALLevel以外の変数で全拒否を制御したほうがあとで不自由しないと思いますが、そこはどのように考えていますか？

**Comment by EibaKatsu** [comment]
独自マケプレ用の ERC 721AP2P は approveを使用していませんが(OpenseaのOperatorFilter用にコードはある)、念の為別の変数にしておきます。
修正後ご連絡します。

**Comment by cryptedy** [comment]
ERC721P2P仕様ならこのままでも問題ないと考えますので、修正についてはお任せします。
（マケプレはあくまで売出し情報を一覧するための場所、という位置づけですかね）

**Comment by EibaKatsu** [comment]
修正しないことにします！
こちらクローズさせていただきます。
