### ISSUE TITLE
pNounsToken.sol 警告対応

### ISSUE THREAD

**Issue by masataka-eth** [EibaKatsu/pNounsGenerative#19]
_processRoyaltyの第二引数は利用しないのであれば削除すればコンパイル警告は消えます

function _processRoyalty(uint256 _salesPrice, uint256 _tokenId)
↓
function _processRoyalty(uint256 _salesPrice, uint256 )

**Comment by EibaKatsu** [comment]
これは継承元のERC721AP2Pの関数をoverrideしたものですが、この中のpurchace関数から呼ばれている時の引数に揃えています。（tokenIdによってロイヤリティを変更できる設計になっていると思います）
引数が違えばoverrideでなくなる認識ですが合っているでしょうか？

```

  function purchase(uint256 _tokenId, address _buyer, address _facilitator) external payable override {
    uint256 price = prices[_tokenId];
    require(price > 0, 'Token is not on sale');
    require(msg.value >= price, 'Not enough fund');
    uint256 comission = _processSalesCommission(msg.value, _facilitator);
    uint256 royalty = _processRoyalty(msg.value, _tokenId);
    address tokenOwner = ownerOf(_tokenId);
    address payable payableTo = payable(tokenOwner);
    payableTo.transfer(msg.value - comission - royalty);

    transferFrom(tokenOwner, _buyer, _tokenId);
    prices[_tokenId] = 0; // not on sale any more
  }

```

**Comment by masataka-eth** [comment]
もちろんoverrideであれば引数を揃える必要があります。
ただ、pNounsではトークンIDごとにロイヤリティ設定はしないのですよね？
なので、引数の型は変えずに_tokenIdの宣言を削除するだけです。_tokenIdが利用されていないのに宣言されているとSolidityにて警告となるので、削除すれば利用されていないことが明確になります。

こちら削除しなくても動作には全く問題ないので、今からだと混乱するだけなのでクローズとしますね。
