### ISSUE TITLE
ストレージへの書き込みについて

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#3]
コンストラクタとmintPNouns()のfor処理の「nextTokenId++」はストレージ書き込みで重いため、forの回数分加算したほうがガス代が安く済みます。(nextTokenId += _mintAmount)

**Comment by EibaKatsu** [comment]
「nextTokenId += _mintAmount」に変更しました！

<img width="953" alt="image" src="https://user-images.githubusercontent.com/98363905/204791226-6aefb235-addd-4cb4-9664-caced8edbf6b.png">

**Comment by EibaKatsu** [comment]
確認ありがとうございます。
↑修正しました。 

コミットコメントで "issue #3" って書いたら勝手にリンクされるんですね、、、凄い。

issueのクローズは issue発行していただいた方で確認後にして貰った方が良さそうですね、、
次からはそうさせていただきます。
