### ISSUE TITLE
オーナーミント無料のrequire()について

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#4]
自分ならオーナーミント無料は念のため「owner() != _msgSender() && admin != _msgSender()」のelseにrequire(msg.value == 0)入れると思います

**Comment by EibaKatsu** [comment]
採用させていただきました！
テストコードも追加しました。

<img width="456" alt="image" src="https://user-images.githubusercontent.com/98363905/204792523-1974cb66-72cc-422d-89fb-714bddbc251f.png">

**Comment by EibaKatsu** [comment]
これだと
オーナーのミントは自由だー
になっちゃってますね。。

**Comment by EibaKatsu** [comment]
"owners mint price is free"　にしました
