### ISSUE TITLE
ユーザー別ミント数上限のカウント方法について

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#5]
ミント数のカウントはプレセール1,2,パブセで共通の認識でよろしいでしょうか？(プレセ1で100枚ミントした人はプレセ2以降は買えない)

**Comment by EibaKatsu** [comment]
プレセール1,2,パブセで共通です。
pNouns投票権の特定アドレスでの占有を防ぎ、保有者を分散させるためです。
（アドレスを分散されたら防ぎようないですが。。。）
