### ISSUE TITLE
1人辺りのミント数上限について

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#6]
市場供給量2000点に対して1人辺り100点ミントは多い気がするのですが、問題ないでしょうか？

**Comment by EibaKatsu** [comment]
目標金額(100ETH)を達成することを第一目的としたため、購入していただける方にはある程度購入して頂こうという狙いです。
この後、第二弾、第三弾まで予定されており、その時に調整することとなっています。
それでも最大100/6000ですが、感覚的にいかがでしょう？

**Comment by hajime001** [comment]
フリーミントではないため購入頂けるなら1人が沢山持つこと自体はOKという方針ですね。
念頭にあったのはCNP(OWNERを出来るだけ分散)で、
オーナー数を増やすのが正というイメージがあったのですが、
売り切るのを主とするならそれでも良いかもしれません。

感覚的にはオーナーを分散させたほうがPJコミュニティの盛り上がりにも
繋がると思っていますが(1人20点×300人ぐらい？)、
PJごとに思想があるのと現時点でのNFTの完全な正解も無いと思うので、
最少で20人になるのが織り込み済みであれば問題ないと思います。

**Comment by cryptedy** [comment]
確かに私もいきなり100枚までミントできるのは気になりました。
AL数にもよりますが、10～20体をミントする人は100人くらいいるかもしれず、一瞬になくなるかも？！
マイナーやバリデーターの分散性がいつも議論になりますが、pNounsも投票権であることを考えると、ある程度分散するほうが好ましいのでは？！
例えばタイムロック的に、1時間ごとにミント上限数を開放していくのはどうでしょう？
5→10→20→40→100
のようにすれば、ある程度少額の人も参加しやすい気がします。

とはいえ、どちらにしても最初のセールは5枚単位でしたっけ？

**Comment by EibaKatsu** [comment]
ご意見ありがとうございます！
ちょっとプロジェクトに持ち帰って再検討してきます。

**Comment by EibaKatsu** [comment]
```
投票5%の上限があるのでそれに即しているので100ミント上限はOK。
もし下げるなら投票上限も下げたほうがいいですが、5%はかなり絶妙。
もしそれが問題になったら、次で改善しましょう！
目的は資金調達なので、特に最初は分散化とか気にする必要は無い
```
ということで、ひとり当たりのミント上限100枚のまま行くことになりました。

ただし、転売ヤーに複数アドレスで買い占められちゃうのは避けたいということで、2022年内はマーケットプレイスでの取引はできないようにすることになりました。
こちらの修正は今日対応予定です。

**Comment by cryptedy** [comment]
なるほど！
であるとすると、transferに5%以下のチェックが必要ですかね。それとも投票システム側で投票力5%超える場合は5%に制限するのですか？ただ、オンチェーンでやるには、ちょっと計算が重い気がします。
・上位ホルダーの抽出
・リミットラインの計算（5%以下になるよう調整）→ニュートン法でokか？
オンチェーンでの実行を考えるとガス代がそこそこかかりそう…（設計方法間違うとガス欠）

**Comment by EibaKatsu** [comment]
ニュートン法、また出てきた。。。(^_^;)

投票システム側はまだ構想段階なのですが、投票の度にガス代かかるのもアレなので、Polygonでやって、
pNounsNFTのスナップショットからPolygonの投票用NFTをGiveawayするオフチェーンプログラムを作る想定です。
このプログラム内で投票力を5%にするような仕組みを考えようかと思っています。

投票数に応じてNFT画像に星をつけるとか面白いかもねー、とかの話が出ています。

**Comment by cryptedy** [comment]
w

了解です。であればコントラクト側でなにかする必要はないですね。
ただ、将来的にやっぱりなにかできるように…という余地を残すのであれば、ITransferControllerみたいなインターフェース用意して、アドレス設定あればbeforeとafterをコールして処理できるようにアップグレード可能にしておくのも手かもしれません

**Comment by EibaKatsu** [comment]
なるほど、、、
これは、ContractAllowListのように、_beforeTokenTransfersの中で
```
        if (address(tc) != address(0)) {
            require(
                tc.isAllowed(from, to) == true,
                "cant transfer"
            );
        }
```
を書くやり方で良いでしょうか？
tcは、ITransferControllerのアドレスです。

参考
https://github.com/masataka-eth/ContractAllowList/blob/main/contracts/ERC721AntiScam/lockable/ERC721Lockable.sol

**Comment by cryptedy** [comment]
それで問題無いと思います！

**Comment by EibaKatsu** [comment]
> ただし、転売ヤーに複数アドレスで買い占められちゃうのは避けたいということで、2022年内はマーケットプレイスでの取引はできないようにすることになりました。
> こちらの修正は今日対応予定です。

時限ロックでなく、運営の任意タイミング（Nouns購入完了 or 返金完了）でロック解除することになりました。
CALコントラクトにまかそうと思いましたが、念の為calLevel==0はNGとするようpNouns側にも記載しました。
96b4040

**Comment by hajime001** [comment]
edyさんassignになってますが、UPの絵文字頂いてるのと自分からも指摘は無いのでクローズしますね。
問題あればまたオープンの形で。
