### ISSUE TITLE
AccessControlの採用推奨

### ISSUE THREAD

**Issue by hajime001** [EibaKatsu/pNounsGenerative#9]
masatakaさんの指摘の拝借ですが
AccessControl入れておくと後から管理者を追加出来るので、中長期的に見た時に運用が楽になると思います。

**Comment by EibaKatsu** [comment]
AccessControlEnumerable を導入しました。 
1389bf3

**Comment by hajime001** [comment]
ご対応ありがとうございます。
setAdminRole()のgrantを_setupRole()でやってますが、
この関数の関数コメントを見る限りコンストラクタで呼び出されるのみを想定してるんじゃないですかね？

内部では_grantRole()を呼んでるだけなので意味は同じで現状問題ないですが、
将来的に何か変更があって他の方がこのコードを参考にされると問題になる可能性あるので、
一応_grantRole()に変えておいたほうが良い気がします。
(この辺り詳しい方がいたら補足頂けると…)

**Comment by EibaKatsu** [comment]
AccessControl.solを読んでみると、_setupRoleはコンストラクタから呼ばれるものと書いてありました。
_grantRoleに変更しました。

**Comment by hajime001** [comment]
修正を確認しました。
